export default {
    DEFAULT_PAGE_SIZE: 100,
    PAGINATION_WIDGET_PAGESOF: [100, 150, 200, 500],
    NUMBER_FORMAT: {
        SEPARADOR_MILES: '.',
        SEPARADOR_DECIMALES: ','
    },
    INT_FORMAT: '0,0',
    DECIMAL_FORMAT: '0,0.00',
    DATE_FORMAT: 'DD-MM-YYYY',
    DATETIME_FORMAT: 'DD-MM-YYYY HH:mm:ss',
    DATETIME_CRAMER_FORMAT: 'MM-DD-YYYY HH:mm:ss',
    DASHBOARD_MAX_NUMBER_OF_TRIALS: 5,
    TOTAL_TRIAL_DECIMALS: 2
};
